### ISSUE TITLE
L02, Line 99 Array initialization

### ISSUE THREAD

**Issue by lilokhang007** [CUHK-ESSC-4510/ESSC4510-2020-Spring#1]
https://github.com/CUHK-ESSC-4510/ESSC4510-2020-Spring/blob/a9e05950854fe217a86cd326abf19d30cd9d8538/L02/L02.py#L99

Excuse me, I wonder if this means np.zeros() instead of np.array() here

**Comment by BenjaminGor** [comment]
Fixed. Thanks.
